[pytest]
DJANGO_SETTINGS_MODULE = config.settings
pythonpath = backend
testpaths = backend/tests
python_files = tests.py test_*.py *_tests.py
addopts =
    --ignore-glob=backend/pytest-cache-files-*
norecursedirs =
    .git
    .next
    .venv
    node_modules
    pytest-cache-files-*
