# Generated by Django 5.2.15 on 2026-06-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_tenant_row_level_security'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_role_assignment_scope',
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('membership', 'role', 'location'), name='unique_location_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', True)), fields=('membership', 'role'), name='unique_org_role_assignment'),
        ),
    ]
